# Generated by Django 4.1.5 on 2023-01-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spcreatemodel',
            old_name='number',
            new_name='phone',
        ),
    ]
