# Generated by Django 4.1.5 on 2023-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_number_spcreatemodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='spuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptname', models.CharField(max_length=30)),
                ('ptid', models.IntegerField()),
                ('ptimage', models.FileField(upload_to='ecomapp/static')),
                ('ptprice', models.IntegerField()),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
    ]
