# Generated by Django 4.1.5 on 2023-01-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_spuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spuploadmodel',
            name='desc',
            field=models.CharField(max_length=60),
        ),
    ]
