# Generated by Django 4.1.5 on 2023-01-31 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0005_usrcreatemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrcreatemodel',
            old_name='name',
            new_name='lastname',
        ),
        migrations.RemoveField(
            model_name='usrcreatemodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='usrcreatemodel',
            name='firstname',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
