# Generated by Django 4.1.5 on 2023-02-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_rename_firstname_usrcreatemodel_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptname', models.CharField(max_length=30)),
                ('ptid', models.IntegerField()),
                ('ptimage', models.FileField(upload_to='ecomapp/static')),
                ('ptprice', models.IntegerField()),
                ('desc', models.CharField(max_length=60)),
            ],
        ),
    ]
